name: Main

on:
  push:
    branches: [main]

jobs:
  build-lint-test:
    name: Validate
    uses: ./.github/workflows/build-lint-test.yml
    secrets:
      RPC_URL_MAINNET_LIST: ${{ secrets.RPC_URL_MAINNET_LIST }}
      RPC_URL_DEVNET_LIST: ${{ secrets.RPC_URL_DEVNET_LIST }}
      RPC_URL_TESTNET_LIST: ${{ secrets.RPC_URL_TESTNET_LIST }}
      RPC_URL_LOCALNET_LIST: ${{ secrets.RPC_URL_LOCALNET_LIST }}
      PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}

  sonarcloud:
    permissions:
      id-token: write
      contents: write
      checks: write
      pull-requests: write
      actions: read
    name: SonarCloud
    needs: build-lint-test
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  pages:
    runs-on: ubuntu-latest
    needs: [build-lint-test]
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore snap build cache
        uses: actions/cache@v3
        with:
          path: ./packages/site/public
          key: site-${{ runner.os }}-${{ github.sha }}
          restore-keys: site-${{ runner.os }}-
      - name: Upload to Github Pages
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./packages/site/public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-completed
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-completed.outputs.PASSED }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi

  is-release:
    # Filtering by `push` events ensures that we only release from the `main` branch, which is a
    # requirement for our npm publishing environment.
    # The commit author should always be 'github-actions' for releases created by the
    # 'create-release-pr' workflow, so we filter by that as well to prevent accidentally
    # triggering a release.
    if: github.event_name == 'push' && startsWith(github.event.head_commit.author.name, 'github-actions')
    needs: all-jobs-pass
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-is-release@v1
        id: is-release

  publish-release:
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    name: Publish release
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RPC_URL_MAINNET_LIST: ${{ secrets.RPC_URL_MAINNET_LIST }}
      RPC_URL_DEVNET_LIST: ${{ secrets.RPC_URL_DEVNET_LIST }}
      RPC_URL_TESTNET_LIST: ${{ secrets.RPC_URL_TESTNET_LIST }}
      RPC_URL_LOCALNET_LIST: ${{ secrets.RPC_URL_LOCALNET_LIST }}
      PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}
