name: PR

on:
  pull_request:

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash) 1.6.23
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} -color
        shell: bash
  build-lint-test:
    name: Validate
    uses: ./.github/workflows/build-lint-test.yml
    secrets:
      RPC_URL_MAINNET_LIST: ${{ secrets.RPC_URL_MAINNET_LIST }}
      RPC_URL_DEVNET_LIST: ${{ secrets.RPC_URL_DEVNET_LIST }}
      RPC_URL_TESTNET_LIST: ${{ secrets.RPC_URL_TESTNET_LIST }}
      RPC_URL_LOCALNET_LIST: ${{ secrets.RPC_URL_LOCALNET_LIST }}
      PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
      LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
      TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}

  sonarcloud:
    permissions:
      id-token: write
      contents: write
      checks: write
      pull-requests: write
      actions: read
    name: SonarCloud
    needs: build-lint-test
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
