name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      RPC_URL_MAINNET_LIST:
        required: true
      RPC_URL_DEVNET_LIST:
        required: true
      RPC_URL_TESTNET_LIST:
        required: true
      RPC_URL_LOCALNET_LIST:
        required: true
      PRICE_API_BASE_URL:
        required: true
      LOCAL_API_BASE_URL:
        required: true
      TOKEN_API_BASE_URL:
        required: true
      STATIC_API_BASE_URL:
        required: true

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: |
          yarn install
          yarn workspace @metamask/solana-wallet-snap build
        env:
          RPC_URL_MAINNET_LIST: ${{ secrets.RPC_URL_MAINNET_LIST }}
          RPC_URL_DEVNET_LIST: ${{ secrets.RPC_URL_DEVNET_LIST }}
          RPC_URL_TESTNET_LIST: ${{ secrets.RPC_URL_TESTNET_LIST }}
          RPC_URL_LOCALNET_LIST: ${{ secrets.RPC_URL_LOCALNET_LIST }}
          PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
          LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
          TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
          STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      - uses: actions/cache@v4
        id: restore-build
        with:
          # We must cache the `snap.manifest.json` file because it might change
          # during the release build due to secrets being injected by the CI.
          path: |
            ./packages/*/dist
            ./packages/snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}

  publish-npm-dry-run:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - uses: actions/cache@v4
        id: restore-build
        with:
          # We must cache the `snap.manifest.json` file because it might change
          # during the release build due to secrets being injected by the CI.
          path: |
            ./packages/*/dist
            ./packages/snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
      - name: Dry Run Publish
        # Omit npm-token token to perform dry-run publish
        uses: MetaMask/action-npm-publish@v4
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subteam: S042S7RE4AE # @metamask-npm-publishers
        env:
          SKIP_PREPACK: true

  publish-npm:
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - uses: actions/cache@v4
        id: restore-build
        with:
          # We must cache the `snap.manifest.json` file because it might change
          # during the release build due to secrets being injected by the CI.
          path: |
            ./packages/*/dist
            ./packages/snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
      - name: Publish
        uses: MetaMask/action-npm-publish@v2
        with:
          # This `NPM_TOKEN` needs to be manually set per-repository.
          # Look in the repository settings under "Environments", and set this token in the `npm-publish` environment.
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true
