name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      RPC_URL_MAINNET_LIST:
        required: true
      RPC_URL_DEVNET_LIST:
        required: true
      RPC_URL_TESTNET_LIST:
        required: true
      RPC_URL_LOCALNET_LIST:
        required: true
      PRICE_API_BASE_URL:
        required: true
      LOCAL_API_BASE_URL:
        required: true
      TOKEN_API_BASE_URL:
        required: true
      STATIC_API_BASE_URL:
        required: true
      SECURITY_ALERTS_API_BASE_URL:
        required: true
      EXPLORER_BASE_URL:
        required: true
jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          yarn install
          yarn workspace @metamask/solana-wallet-snap build
        env:
          ENVIRONMENT: production
          RPC_URL_MAINNET_LIST: ${{ secrets.RPC_URL_MAINNET_LIST }}
          RPC_URL_DEVNET_LIST: ${{ secrets.RPC_URL_DEVNET_LIST }}
          RPC_URL_TESTNET_LIST: ${{ secrets.RPC_URL_TESTNET_LIST }}
          RPC_URL_LOCALNET_LIST: ${{ secrets.RPC_URL_LOCALNET_LIST }}
          EXPLORER_BASE_URL: ${{ secrets.EXPLORER_BASE_URL }}
          PRICE_API_BASE_URL: ${{ secrets.PRICE_API_BASE_URL }}
          LOCAL_API_BASE_URL: ${{ secrets.LOCAL_API_BASE_URL }}
          TOKEN_API_BASE_URL: ${{ secrets.TOKEN_API_BASE_URL }}
          STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
          SECURITY_ALERTS_API_BASE_URL: ${{ secrets.SECURITY_ALERTS_API_BASE_URL }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
          include-hidden-files: true
          retention-days: 4
          path: |
            ./packages/**/dist
            ./packages/snap/snap.manifest.json
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}

  publish-npm-dry-run:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Dry Run Publish
        uses: MetaMask/action-npm-publish@v4
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subteam: S042S7RE4AE # @metamask-npm-publishers
        env:
          SKIP_PREPACK: true

  publish-npm:
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Publish
        uses: MetaMask/action-npm-publish@v2
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true
