name: Validate application code

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write
  actions: read

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      sonar_token:
        description: SonarCloud token
        required: true

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: coverage
          pattern: tests-artifacts-*
          merge-multiple: true
      - name: Display structure of downloaded files
        run: |
          if [ -d coverage ]; then
            ls -R coverage
          fi
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
